

Gracias a @nfranklin me di cuenta de cuál era el problema. Por lo que vale la pena resolver el problema, tuve que instalar una de las últimas versiones de refuerzo, se me ocurrió el siguiente travis.ymlscript.

language: cpp

compiler:
  - g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev
    - cmake

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8 -std=c++11 -DENABLE_REINFORCEMENT_LEARNING" CC="gcc-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make 